name: Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/**'

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: 'true'
  # GIT_SSH_COMMAND: 'ssh -o UserKnownHostsFile=/github/home/.ssh/known_hosts -o StrictHostKeyChecking=yes'

jobs:
  ci:
    name: CI - Node.js ${{ matrix.node-version }} & Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '20'
          - '22'
          - '24'
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
            ${{ secrets.HTTP_HANDLER_ACCESS_TOKEN }}
            ${{ secrets.HTTP_REWRITER_ACCESS_TOKEN }}
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: node-modules-${{ hashFiles('package.json') }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      # TODO: replace with `pnpm install` when using published dependency
      - name: Build python-node manually
        run: |
          # Configure git to use SSH host aliases for private repos (needed by cargo)
          git config --global url."ssh://git@github.com-http-handler/platformatic/http-handler".insteadOf "ssh://git@github.com/platformatic/http-handler"
          git config --global url."ssh://git@github.com-http-handler/platformatic/http-handler.git".insteadOf "ssh://git@github.com/platformatic/http-handler.git"
          git config --global url."ssh://git@github.com-http-rewriter/platformatic/http-rewriter".insteadOf "ssh://git@github.com/platformatic/http-rewriter"
          git config --global url."ssh://git@github.com-http-rewriter/platformatic/http-rewriter.git".insteadOf "ssh://git@github.com/platformatic/http-rewriter.git"

          cd node_modules/@platformatic/python-node
          pnpm install --ignore-scripts
          pnpm run build
          pnpm run build:wasm
          pnpm run build:fix
      - name: Run Full Test Suite
        shell: bash
        run: pnpm test
