name: Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  ci:
    name: CI - Node.js ${{ matrix.node-version }} & Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '22'
          - '24'
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.PYTHON_NODE_NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PYTHON_NODE_NPM_TOKEN }}
      - name: Run Full Test Suite
        shell: bash
        run: pnpm test
